### ISSUE TITLE
Help needed regarding nix-shell 

### ISSUE THREAD

**Issue by abhi18av** [griff/nixos-vagrant#1]
Hi @griff 

I am trying to explore NixOS in a Vagrant environment and I found your vagrant-box for NixOS here https://app.vagrantup.com/griff/boxes/nixos-18.03-x86_64

I installed it and `ssh` into it only to run into this error

```
[vagrant@nixos:~]$ nix-shell 
error: getting status of '/home/vagrant/default.nix': No such file or directory

```

I'd like to set this specific virtualbox for Haskell development - could you please help me out a bit ?

**Comment by griff** [comment]
Have you looked at https://nixos.org/nixpkgs/manual/#how-to-create-a-development-environment

**Comment by griff** [comment]
Normally when you invoke `nix-shell` (which starts a new shell with a clean environment containing packages and such) it either looks for a `default.nix` or `shell.nix` in current directory otherwise you need to specify as arguments to `nix-shell` what you want the new shell environment to contain.

**Comment by griff** [comment]
There are some more examples of how to use `nix-shell` for Haskell development here: https://nixos.org/nixpkgs/manual/#how-to-create-ad-hoc-environments-for-nix-shell

**Comment by abhi18av** [comment]
Oh, I see.

In the meantime I've tried to install stack in nix-shell corresponding to version v8.4.3 and I got to know that perhaps there is an issue with that specific version. 

I'd like to know if there's a way to install stack corresponding to version v8.2.2 as I do know that it's an LTS and works fine on my mac as well. Please let me out a bit :)

**Comment by abhi18av** [comment]
Oh, I see.

In the meantime I've tried to install stack in nix-shell corresponding to version v8.4.3 and I got to know that perhaps there is an issue with that specific version. 

I'd like to know if there's a way to install stack corresponding to version v8.2.2 as I do know that it's an LTS and works fine on my mac as well. Please let me out a bit :)

**Comment by griff** [comment]
There is a way to use v8.2.2. But could you paste how you installed v8.4.3 in nix-shell by either giving me the command line you used or the `shell.nix` file you used? I ask because there are different ways you could have installed stack and for me to tell you what you need to change to instead use v8.2.2 I need to see which method you used.

**Comment by griff** [comment]
I am going to close this as it is not exactly related to the vagrant box
